class CurrencyInitialData {

    def getCurrencies() {
        def list = []

        list << [name: 'Afghanistan afghani', code: 'AFA', decimals: 2, autoUpdate: false]
        list << [name: 'Albanian lek', code: 'ALL', decimals: 2, autoUpdate: true]
        list << [name: 'Algerian dinar', code: 'DZD', decimals: 0, autoUpdate: true]
        list << [name: 'Angolan kwanza', code: 'AOA', decimals: 2, autoUpdate: false]
        list << [name: 'Argentine peso', code: 'ARS', decimals: 2, autoUpdate: true]
        list << [name: 'Armenian dram', code: 'AMD', decimals: 2, autoUpdate: false]
        list << [name: 'Aruban guilder', code: 'AWG', decimals: 2, autoUpdate: true]
        list << [name: 'Australian dollar', code: 'AUD', decimals: 2, autoUpdate: true]
        list << [name: 'Azerbaijanian new manat', code: 'AZN', decimals: 2, autoUpdate: false]
        list << [name: 'Bahamian dollar', code: 'BSD', decimals: 2, autoUpdate: true]
        list << [name: 'Bahraini dinar', code: 'BHD', decimals: 3, autoUpdate: true]
        list << [name: 'Bangladeshi taka', code: 'BDT', decimals: 2, autoUpdate: true]
        list << [name: 'Barbados dollar', code: 'BBD', decimals: 2, autoUpdate: true]
        list << [name: 'Belarusian ruble', code: 'BYR', decimals: 2, autoUpdate: true]
        list << [name: 'Belize dollar', code: 'BZD', decimals: 2, autoUpdate: true]
        list << [name: 'Bermudian dollar', code: 'BMD', decimals: 2, autoUpdate: true]
        list << [name: 'Bhutan ngultrum', code: 'BTN', decimals: 2, autoUpdate: true]
        list << [name: 'Bolivian boliviano', code: 'BOB', decimals: 2, autoUpdate: true]
        list << [name: 'Botswana pula', code: 'BWP', decimals: 2, autoUpdate: true]
        list << [name: 'Brazilian real', code: 'BRL', decimals: 2, autoUpdate: true]
        list << [name: 'British pound', code: 'GBP', decimals: 2, autoUpdate: true]
        list << [name: 'Brunei dollar', code: 'BND', decimals: 2, autoUpdate: true]
        list << [name: 'Bulgarian lev', code: 'BGN', decimals: 2, autoUpdate: true]
        list << [name: 'Burundi franc', code: 'BIF', decimals: 2, autoUpdate: true]
        list << [name: 'Cambodian riel', code: 'KHR', decimals: 2, autoUpdate: false]
        list << [name: 'Canadian dollar', code: 'CAD', decimals: 2, autoUpdate: true]
        list << [name: 'Cape Verde escudo', code: 'CVE', decimals: 2, autoUpdate: false]
        list << [name: 'Cayman Islands dollar', code: 'KYD', decimals: 2, autoUpdate: true]
        list << [name: 'CFA franc BCEAO', code: 'XOF', decimals: 2, autoUpdate: true]
        list << [name: 'CFA franc BEAC', code: 'XAF', decimals: 2, autoUpdate: true]
        list << [name: 'CFP franc', code: 'XPF', decimals: 2, autoUpdate: false]
        list << [name: 'Chilean peso', code: 'CLP', decimals: 2, autoUpdate: true]
        list << [name: 'Chinese yuan renminbi', code: 'CNY', decimals: 1, autoUpdate: true]
        list << [name: 'Colombian peso', code: 'COP', decimals: 2, autoUpdate: true]
        list << [name: 'Comoros franc', code: 'KMF', decimals: 2, autoUpdate: true]
        list << [name: 'Congolese franc', code: 'CDF', decimals: 2, autoUpdate: false]
        list << [name: 'Costa Rican colon', code: 'CRC', decimals: 2, autoUpdate: true]
        list << [name: 'Croatian kuna', code: 'HRK', decimals: 2, autoUpdate: true]
        list << [name: 'Cuban peso', code: 'CUP', decimals: 2, autoUpdate: true]
        list << [name: 'Czech koruna', code: 'CZK', decimals: 2, autoUpdate: true]
        list << [name: 'Danish krone', code: 'DKK', decimals: 2, autoUpdate: true]
        list << [name: 'Djibouti franc', code: 'DJF', decimals: 2, autoUpdate: false]
        list << [name: 'Dominican peso', code: 'DOP', decimals: 2, autoUpdate: true]
        list << [name: 'East Caribbean dollar', code: 'XCD', decimals: 2, autoUpdate: true]
        list << [name: 'Egyptian pound', code: 'EGP', decimals: 2, autoUpdate: true]
        list << [name: 'El Salvador colon', code: 'SVC', decimals: 2, autoUpdate: true]
        list << [name: 'Eritrean nakfa', code: 'ERN', decimals: 2, autoUpdate: false]
        list << [name: 'Estonian kroon', code: 'EEK', decimals: 2, autoUpdate: true]
        list << [name: 'Ethiopian birr', code: 'ETB', decimals: 2, autoUpdate: true]
        list << [name: 'EU euro', code: 'EUR', decimals: 2, autoUpdate: true]
        list << [name: 'Falkland Islands pound', code: 'FKP', decimals: 2, autoUpdate: false]
        list << [name: 'Fiji dollar', code: 'FJD', decimals: 2, autoUpdate: true]
        list << [name: 'Gambian dalasi', code: 'GMD', decimals: 2, autoUpdate: true]
        list << [name: 'Georgian lari', code: 'GEL', decimals: 2, autoUpdate: false]
        list << [name: 'Ghanaian new cedi', code: 'GHS', decimals: 2, autoUpdate: false]
        list << [name: 'Gibraltar pound', code: 'GIP', decimals: 2, autoUpdate: false]
        list << [name: 'Guatemalan quetzal', code: 'GTQ', decimals: 2, autoUpdate: true]
        list << [name: 'Guinean franc', code: 'GNF', decimals: 2, autoUpdate: true]
        list << [name: 'Guyana dollar', code: 'GYD', decimals: 2, autoUpdate: false]
        list << [name: 'Haitian gourde', code: 'HTG', decimals: 2, autoUpdate: true]
        list << [name: 'Honduran lempira', code: 'HNL', decimals: 2, autoUpdate: true]
        list << [name: 'Hong Kong dollar', code: 'HKD', decimals: 2, autoUpdate: true]
        list << [name: 'Hungarian forint', code: 'HUF', decimals: 2, autoUpdate: true]
        list << [name: 'Icelandic krona', code: 'ISK', decimals: 2, autoUpdate: true]
        list << [name: 'Indian rupee', code: 'INR', decimals: 2, autoUpdate: true]
        list << [name: 'Indonesian rupiah', code: 'IDR', decimals: 0, autoUpdate: true]
        list << [name: 'Iranian rial', code: 'IRR', decimals: 0, autoUpdate: true]
        list << [name: 'Iraqi dinar', code: 'IQD', decimals: 3, autoUpdate: true]
        list << [name: 'Israeli new shekel', code: 'ILS', decimals: 2, autoUpdate: true]
        list << [name: 'Jamaican dollar', code: 'JMD', decimals: 2, autoUpdate: true]
        list << [name: 'Japanese yen', code: 'JPY', decimals: 0, autoUpdate: true]
        list << [name: 'Jordanian dinar', code: 'JOD', decimals: 3, autoUpdate: true]
        list << [name: 'Kazakh tenge', code: 'KZT', decimals: 2, autoUpdate: true]
        list << [name: 'Kenyan shilling', code: 'KES', decimals: 2, autoUpdate: true]
        list << [name: 'Kuwaiti dinar', code: 'KWD', decimals: 3, autoUpdate: true]
        list << [name: 'Kyrgyz som', code: 'KGS', decimals: 2, autoUpdate: false]
        list << [name: 'Lao kip', code: 'LAK', decimals: 2, autoUpdate: false]
        list << [name: 'Latvian lats', code: 'LVL', decimals: 2, autoUpdate: true]
        list << [name: 'Lebanese pound', code: 'LBP', decimals: 0, autoUpdate: true]
        list << [name: 'Lesotho loti', code: 'LSL', decimals: 2, autoUpdate: true]
        list << [name: 'Liberian dollar', code: 'LRD', decimals: 2, autoUpdate: false]
        list << [name: 'Libyan dinar', code: 'LYD', decimals: 3, autoUpdate: false]
        list << [name: 'Lithuanian litas', code: 'LTL', decimals: 2, autoUpdate: true]
        list << [name: 'Macao pataca', code: 'MOP', decimals: 2, autoUpdate: true]
        list << [name: 'Macedonian denar', code: 'MKD', decimals: 2, autoUpdate: true]
        list << [name: 'Malagasy ariary', code: 'MGA', decimals: 2, autoUpdate: false]
        list << [name: 'Malawi kwacha', code: 'MWK', decimals: 2, autoUpdate: true]
        list << [name: 'Malaysian ringgit', code: 'MYR', decimals: 2, autoUpdate: true]
        list << [name: 'Maldivian rufiyaa', code: 'MVR', decimals: 2, autoUpdate: true]
        list << [name: 'Mauritanian ouguiya', code: 'MRO', decimals: 1, autoUpdate: true]
        list << [name: 'Mauritius rupee', code: 'MUR', decimals: 2, autoUpdate: true]
        list << [name: 'Mexican peso', code: 'MXN', decimals: 2, autoUpdate: true]
        list << [name: 'Moldovan leu', code: 'MDL', decimals: 0, autoUpdate: true]
        list << [name: 'Mongolian tugrik', code: 'MNT', decimals: 2, autoUpdate: true]
        list << [name: 'Moroccan dirham', code: 'MAD', decimals: 2, autoUpdate: true]
        list << [name: 'Mozambique new metical', code: 'MZN', decimals: 2, autoUpdate: false]
        list << [name: 'Myanmar kyat', code: 'MMK', decimals: 2, autoUpdate: false]
        list << [name: 'Namibian dollar', code: 'NAD', decimals: 2, autoUpdate: true]
        list << [name: 'Nepalese rupee', code: 'NPR', decimals: 2, autoUpdate: true]
        list << [name: 'Netherlands Antillian guilder', code: 'ANG', decimals: 2, autoUpdate: true]
        list << [name: 'New Zealand dollar', code: 'NZD', decimals: 2, autoUpdate: true]
        list << [name: 'Nicaraguan cordoba oro', code: 'NIO', decimals: 2, autoUpdate: true]
        list << [name: 'Nigerian naira', code: 'NGN', decimals: 2, autoUpdate: true]
        list << [name: 'North Korean won', code: 'KPW', decimals: 2, autoUpdate: false]
        list << [name: 'Norwegian krone', code: 'NOK', decimals: 2, autoUpdate: true]
        list << [name: 'Omani rial', code: 'OMR', decimals: 3, autoUpdate: true]
        list << [name: 'Pakistani rupee', code: 'PKR', decimals: 2, autoUpdate: true]
        list << [name: 'Panamanian balboa', code: 'PAB', decimals: 2, autoUpdate: true]
        list << [name: 'Papua New Guinea kina', code: 'PGK', decimals: 2, autoUpdate: true]
        list << [name: 'Paraguayan guarani', code: 'PYG', decimals: 2, autoUpdate: true]
        list << [name: 'Peruvian nuevo sol', code: 'PEN', decimals: 2, autoUpdate: true]
        list << [name: 'Philippine peso', code: 'PHP', decimals: 2, autoUpdate: true]
        list << [name: 'Polish zloty', code: 'PLN', decimals: 2, autoUpdate: true]
        list << [name: 'Qatari rial', code: 'QAR', decimals: 2, autoUpdate: true]
        list << [name: 'Romanian new leu', code: 'RON', decimals: 2, autoUpdate: true]
        list << [name: 'Russian ruble', code: 'RUB', decimals: 2, autoUpdate: true]
        list << [name: 'Rwandan franc', code: 'RWF', decimals: 2, autoUpdate: true]
        list << [name: 'Saint Helena pound', code: 'SHP', decimals: 2, autoUpdate: false]
        list << [name: 'Samoan tala', code: 'WST', decimals: 2, autoUpdate: true]
        list << [name: 'Sao Tome and Principe dobra', code: 'STD', decimals: 2, autoUpdate: true]
        list << [name: 'Saudi riyal', code: 'SAR', decimals: 2, autoUpdate: true]
        list << [name: 'Serbian dinar', code: 'RSD', decimals: 2, autoUpdate: false]
        list << [name: 'Seychelles rupee', code: 'SCR', decimals: 2, autoUpdate: true]
        list << [name: 'Sierra Leone leone', code: 'SLL', decimals: 2, autoUpdate: true]
        list << [name: 'Singapore dollar', code: 'SGD', decimals: 2, autoUpdate: true]
        list << [name: 'Slovak koruna', code: 'SKK', decimals: 2, autoUpdate: true]
        list << [name: 'Solomon Islands dollar', code: 'SBD', decimals: 2, autoUpdate: true]
        list << [name: 'Somali shilling', code: 'SOS', decimals: 2, autoUpdate: false]
        list << [name: 'South African rand', code: 'ZAR', decimals: 2, autoUpdate: true]
        list << [name: 'South Korean won', code: 'KRW', decimals: 0, autoUpdate: true]
        list << [name: 'Sri Lanka rupee', code: 'LKR', decimals: 2, autoUpdate: true]
        list << [name: 'Sudanese pound', code: 'SDG', decimals: 2, autoUpdate: false]
        list << [name: 'Suriname dollar', code: 'SRD', decimals: 2, autoUpdate: false]
        list << [name: 'Swaziland lilangeni', code: 'SZL', decimals: 2, autoUpdate: true]
        list << [name: 'Swedish krona', code: 'SEK', decimals: 2, autoUpdate: true]
        list << [name: 'Swiss franc', code: 'CHF', decimals: 2, autoUpdate: true]
        list << [name: 'Syrian pound', code: 'SYP', decimals: 2, autoUpdate: false]
        list << [name: 'Taiwan New dollar', code: 'TWD', decimals: 2, autoUpdate: true]
        list << [name: 'Tajik somoni', code: 'TJS', decimals: 2, autoUpdate: false]
        list << [name: 'Tanzanian shilling', code: 'TZS', decimals: 2, autoUpdate: true]
        list << [name: 'Thai baht', code: 'THB', decimals: 2, autoUpdate: true]
        list << [name: "Tongan pa'anga", code: 'TOP', decimals: 2, autoUpdate: true]
        list << [name: 'Trinidad and Tobago dollar', code: 'TTD', decimals: 2, autoUpdate: true]
        list << [name: 'Tunisian dinar', code: 'TND', decimals: 3, autoUpdate: true]
        list << [name: 'Turkish lira', code: 'TRY', decimals: 2, autoUpdate: true]
        list << [name: 'Turkmen manat', code: 'TMM', decimals: 2, autoUpdate: false]
        list << [name: 'UAE dirham', code: 'AED', decimals: 2, autoUpdate: true]
        list << [name: 'Uganda new shilling', code: 'UGX', decimals: 2, autoUpdate: true]
        list << [name: 'Ukrainian hryvnia', code: 'UAH', decimals: 2, autoUpdate: true]
        list << [name: 'Uruguayan peso', code: 'UYU', decimals: 2, autoUpdate: true]
        list << [name: 'US dollar', code: 'USD', decimals: 2, autoUpdate: true]
        list << [name: 'Uzbekistani sum', code: 'UZS', decimals: 0, autoUpdate: false]
        list << [name: 'Vanuatu vatu', code: 'VUV', decimals: 2, autoUpdate: true]
        list << [name: 'Venezuelan bolivar', code: 'VEB', decimals: 2, autoUpdate: true]
        list << [name: 'Vietnamese dong', code: 'VND', decimals: 2, autoUpdate: true]
        list << [name: 'Yemeni rial', code: 'YER', decimals: 0, autoUpdate: true]
        list << [name: 'Zambian kwacha', code: 'ZMK', decimals: 0, autoUpdate: true]
        list << [name: 'Zimbabwe dollar', code: 'ZWD', decimals: 0, autoUpdate: true]
        list << [name: 'Convertible Marks', code: 'BAM', decimals: 2, autoUpdate: false]

        return list
    }
}

